### ISSUE TITLE
The column 'Column1' of the table was not found

### ISSUE THREAD

**Issue by prak2419** [Azure/CCOInsights#228]
**Describe the bug**
Loading the CCO dashboard fails with error 'The column 'Column1' of the table was not found'

**To Reproduce**
1. Open the CCOInfradashboard v9.1.pbit file
2. Enter the org. credentials

**Expected behavior**
Powerbi dashboard for Azure Infra

**Screenshots**
![cco_error](https://user-images.githubusercontent.com/41781768/160113965-9817c5e6-bada-4829-9fea-7def07602595.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - PowerBI Version: 2.103.661.0

**Additional context**
The user is signing in with the organizational account with proper credentials. We tried clearing all the credentials and reload still no luck.

**Comment by trdvangraft** [comment]
I am facing similar issues! Lets keep each other posted on progress

**Comment by kukisama** [comment]
I encountered the same problem and tried several versions, but they are still unavailable.
I tried to use three accounts, none of which is available:

@live. Cn users
onmicrosoft. Users under com
New account under custom domain name

Global administrator permissions are configured and are still unavailable.

**Comment by josunefon** [comment]
You need to have RBAC permissions at subscription or MG level, AD tenant permissions are required to retrieve data from users/spns (GRAPH API)

**Comment by prak2419** [comment]
The user has owner permissions at the subscription level and he is a global administrator for their Azure AD. Still, the page doesn't load and ends up with the same error.

**Comment by josunefon** [comment]
@prak2419 can you try with the latest 9.1 version updated 14 days ago?

**Comment by mosorio29** [comment]
Hi everyone,

Did you find the solution for this? I am facing the same problem. I already installed the latest version, but I am getting the same issue.

**Comment by josunefon** [comment]
Hi @mosorio29 did you check https://github.com/Azure/CCOInsights/issues/105#issuecomment-666220426 ?

**Comment by josunefon** [comment]
closing the issue after no response provided
