### ISSUE TITLE
Refresh dashboard in Power BI Service

### ISSUE THREAD

**Issue by dinesh-mna** [Azure/CCOInsights#238]
Hi Team,

We have been trying to setup refresh using power BI service and it seems there is limitation to setup scheduled refresh/refresh from power BI service for Dynamic Data source. It fails with the message "This dataset includes a dynamic data source. Since dynamic data sources aren't refreshed in the Power BI service, this dataset won't be refreshed. Learn more: https://aka.ms/dynamic-data-sources.".

Is there any workaround to solve this issue (or) we have to refresh the data source everytime from PowerBI Desktop and Publish it again?

Thanks

**Comment by Nickelodeon111** [comment]
Issue lies with the functions (fx ListRecommendations , fx ListAdvisorScore , etc.) in the Power BI template (CCOInfradashboard v9.1), they don't allow refresh from the Power BI service (cloud), you can only refresh from Power BI Desktop.

**Comment by josunefon** [comment]
Hi @Nickelodeon111 currently the CCO Insight dashboard is only supported on Power BI desktop, the team is working to onboard a new solution with Power BI Online support. https://github.com/Azure/CCOInsights/issues/230#issuecomment-1112198356
