### ISSUE TITLE
Icons does not display

### ISSUE THREAD

**Issue by emarana** [Azure/CCOInsights#249]
**Describe the bug**
All icon images links are broken

**To Reproduce**
1. Go to 'AKS dashboard -> Overview'
2. Check on top rigth  'Security Center Recommedations....'
3. See the missing icons

You can also reproduce in the main tab of the Governance report (under "Hierarchy Overview") besides Infra ("Overview" tab on Top 10 Azure Advisor)
Please note, the icon url in the report is: https://azure.github.io/ccodashboard/assets/2020_Icons/Policy.svg (giving 404)
..but in the CCO repo is: https://github.com/Azure/CCOInsights/blob/master/docs/assets/2020_Icons/Policy.svg

**Expected behavior**
It should display the icon, aren't they? 

**Screenshots**
![image](https://user-images.githubusercontent.com/16290744/177858098-93caa7df-deac-4a68-a306-81ece06a3f81.png)
![image](https://user-images.githubusercontent.com/16290744/177859279-a3342400-691d-4f1d-a195-7c0d57c21f23.png)
![image](https://user-images.githubusercontent.com/16290744/177861076-93dd6b5e-3817-467b-9366-f1f235b0ea0c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise 21H2
 - Browser Microsoft Edge Version 103.0.1264.44 (Official build) (64-bit)
 - Version: Version: 2.106.883.0 64-bit (June 2022)

**Additional context**
I found these broken links in the AKS, Infra and Governance reports. Didn't see any other issue related, that's why I have opened. 

Thank you in advance.

**Comment by Nickelodeon111** [comment]
In the Power BI template (CCOInfradashboard v9.1) the link for icons is:   https://azure.github.io/ccodashboard/assets/2020_Icons/     
If you browse it you get error 404 Not found.

This URL gives the icons: https://github.com/Azure/CCOInsights/tree/master/docs/assets/2020_Icons/ 
but even if you use it you still don't get the image displayed in the Power BI template. 

Another issue, if I refresh the table 'Get Recommendations', then 'Azure Advisor' page no longer shows the Security icon under the Category visual. The other 4 are not affected (HighAvailability, OperationalExcellence, Performance, Cost)

**Comment by josunefon** [comment]
Hi @Nickelodeon111 sadly the AKS dashboard is not maintained anymore, we changed the name of the repo and this is why the images are not being displayed.

The Infra and governance dashboards were modified to point to the correct links

**Comment by Nickelodeon111** [comment]
> Hi @Nickelodeon111 sadly the AKS dashboard is not maintained anymore, we changed the name of the repo and this is why the images are not being displayed.
> 
> The Infra and governance dashboards were modified to point to the correct links

 Do I need to download a newer version of the Power BI template (CCOInfradashboard v9.1) or will a refresh fix it.
