### ISSUE TITLE
Issue with few images in Power BI service

### ISSUE THREAD

**Issue by alurisreedhar1** [Azure/CCOInsights#254]
**Describe the bug**
issue with some of the icons after publishing the report to Power BI service
**To Reproduce**
Upload the dashboard to Power BI desktop and publish it to power BI service. 
An example below from the Governance dashboard:

![image](https://user-images.githubusercontent.com/98109209/180096602-a8f7bac4-7efa-4aa7-b9c9-72cf9cd20795.png)

**Expected behavior**
ideally it should have same view as in desktop

**Screenshots**
added

**Desktop (please complete the following information):**
Win10

**Smartphone (please complete the following information):**
N/A

**Additional context**
similar issue on infa dashboard security panel

Please let me know if it due to admin settings where these are restricted or if there is a workaround which can be used.

**Comment by josunefon** [comment]
Hi @alurisreedhar1,

We just imported the visual from the marketplace. Maybe you need to ask to the admins in your organization or create an issue to the owners of the visual: 

![image](https://user-images.githubusercontent.com/39730064/180793251-583eaf83-0977-4c63-8666-2ea64db8fd4d.png)

Hope it helps :)
