### ISSUE TITLE
CCO Azure Governance Dashboard Version 2.6 Still has broken links to SVG files

### ISSUE THREAD

**Issue by jag-sandhu** [Azure/CCOInsights#258]
CCO Azure Governance Dashboard Version 2.6 still has broken links to SVG files,w hicvh have since moved repos e.g.

https://azure.github.io/ccodashboard/assets/2020_Icons/StorageAccount.svg

![image](https://user-images.githubusercontent.com/47786950/183435702-c7aba513-171f-4c58-bbd3-4cee70cebe2d.png)

**Comment by josunefon** [comment]
Fixed with the new release, all the URIs are linked to the CCOInsights repo.
