### ISSUE TITLE
Governance dashboard-Azure policies

### ISSUE THREAD

**Issue by mpalagir** [Azure/CCOInsights#260]
Hi team,

Please help me understand why dashboard is not reflecting the details of azure custom policies. It is only reflecting the built-in policies. Do we have any upgraded version of this governance dashboard?

**Comment by TomazMlakar** [comment]
We are aware of that and working on updating the dashboard showing the correct numbers in Policies section.

**Comment by mpalagir** [comment]
Thanks for the response Tomaz. Kindly let us know once if it is fixed.

**Comment by josunefon** [comment]
Hi @mpalagir, we have the fix of the issue in a PR pending to be approved. You can download the last template from [here](https://github.com/Azure/CCOInsights/raw/c50b614986f34fe1dc5981f4ff17be4d28fc5739/dashboards/CCODashboard-Governance/CCO%20Power%20BI%20governance%20dashboard%20v2.7.pbit)

**Comment by mpalagir** [comment]
Hi @josunefon,

Thank you so much for the prompt update. Let me please cross check the data and will reach out your help, if anything needed.

Thank you,
Warm regards,
Mahesh.
