### ISSUE TITLE
Mismatch in the count-CCO Infrastructure Dashboard

### ISSUE THREAD

**Issue by mpalagir** [Azure/CCOInsights#261]
Hi Team,

Greetings!!

This is to kindly update you that, there is some mismatch in the count of data it is reflecting in the power bi dashboard to actual count of the data from azure portal. We have 137 key vault resources in azure where as dashboard showing 122 only also vms we have 131 but dashboard showing 137.

Can you please help us understand this behavior. Otherwise it is great innovation interms of consolidating the all data at one place.

Thank you.

**Comment by TomazMlakar** [comment]
After checking we clarified that:
- the key icon in the Overview is showing the number of subscriptions and not Key Vaults.
- refreshing the VM data source is showing the same number of resources as in Azure Portal.
