### ISSUE TITLE
Azure Security Benchmark V3 needs to be added

### ISSUE THREAD

**Issue by nusairi** [Azure/CCOInsights#263]
Hi , 
looks like on Governance Dashboard currently we do not have Azure security benchmark V3 . Can this be added.

**Comment by josunefon** [comment]
Hi @nusairi,

Currently the API is not returning the Azure Security Benchmark v3 as a regulatory standard, but it can be shown as a policy set if you modify the regulatory standard table filters.

Hopefully the PG will change this soon :)
