### ISSUE TITLE
CCO Infrastructure dashboard queries/bugs

### ISSUE THREAD

**Issue by maheswara321** [Azure/CCOInsights#265]
Dear @josunefon,

Thanks for your effort in building this dashboard.

Could you please fix these errors.

1.From the overview section-->Subscription owners details. As discussed, count of the owners details in the visualization of Subscription owners not reflecting correctly. Can you please fix this?
2.Can you help me understand what this count is here( 171 highlited)? This is from NSG tabs
![image](https://user-images.githubusercontent.com/108669471/186145742-4d6d4118-d4b5-49dc-b77b-c644c698abce.png)

Based on name of the visualization, I am assuming this count may be the count of ACLs/rules count part of NSG. Please confirm? If this is part of NSG then i am wondering we don't have 170+ rules for any NSG. If they are not acls please help us know of these?

3. When it comes to RBAC i think we have RBAC permissions, I understand these are the users details scoped under subscription level. Can we reflect the user details that are part of tenant level as well?

Looking forward to hearing from you on this.

Thank you,
Warm regards,
Mahes.

**Comment by josunefon** [comment]
1.  Already fixed, now we're showing the data from the correct table "RBAC Role SP, Users and Groups"
2. This number is the count of all the rules for each NSG
![image](https://user-images.githubusercontent.com/39730064/194912910-2befbaa9-1ba2-4080-bbcf-8cdd2b3166e5.png)

3. This feature is not available yet
