### ISSUE TITLE
Usage % :: the sum of the column "Usage %" doesn't reach 100%

### ISSUE THREAD

**Issue by francesco1119** [Azure/CCOInsights#267]
**Describe the bug**
I'm using your dashboard but I find it hard to use. 
I don't understand the meaning of the columns: 

- Current Usage
- Limit
- Usage % 

Plus the "Usage %" column has a bug because the sum of all entries doesn't reach 100% 

**To Reproduce**
1. Go to IaaS Usage and Limits page
2. Check if the sum of all data in the "Usage %" column reach the 100%

**Expected behavior**
The sum of all data in the "Usage %" column should reach the 100%

**Screenshots**

![Usage](https://user-images.githubusercontent.com/3397477/187218891-a9b17fd9-6dbf-4fdf-b757-952ab03373f4.png)

**Desktop (please complete the following information):**
 - Browser: Chrome

**Comment by josunefon** [comment]
Hi @francesco1119 

This is how the visual works:

**Current usage** is the number of resources that are in your environment, for example: **114** for Standard ESv3 Family vCPUs

**Limit** is the maximum quota allowed for this type of resource,  for example: **1050** for Standard ESv3 Family vCPUs

**Usage** is the percentage of quota consumed (it works for each row), for example (114*100)/1050 = **10'86%**

**Comment by francesco1119** [comment]
Thank you so much.

So 10'86% is the Average usage per Month or what we have used since the beginning of the year? 
This will help me better understand this metric.
