### ISSUE TITLE
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.

### ISSUE THREAD

**Issue by cybersh3ll** [Azure/CCOInsights#268]
I've followed the install instructions but I've recived the following error:

![image](https://user-images.githubusercontent.com/106491758/187649458-18051852-08f7-405e-9b73-47769be22c47.png)
![image](https://user-images.githubusercontent.com/106491758/187649486-8ec397fb-69d4-4c1f-a3ff-8941487097c5.png)
![image](https://user-images.githubusercontent.com/106491758/187649526-d3f4780c-054d-4f1a-a7c0-d249dde8611c.png)
![image](https://user-images.githubusercontent.com/106491758/187649571-085beea3-fc3c-4100-a48f-9bd3a987fe9f.png)

**Comment by adamswbrown** [comment]
I am also seeing this issue, is there a resolution? - I dont see any other data sources aside from the Management address (that I have set to Org permission stratus as per docs)

**Comment by josunefon** [comment]
Please check the privacy settings: https://github.com/Azure/CCOInsights/blob/main/dashboards/CCODashboard-Governance/GovernanceDeploymentGuide.md#modify-privacy-settings

This is a known issue: https://github.com/Azure/CCOInsights/issues/105#issuecomment-676399216
