### ISSUE TITLE
Switch Tenants when using an account that has access to multiple tenants

### ISSUE THREAD

**Issue by CarlH2** [Azure/CCOInsights#270]
I am a support professional that has minimal to no rights in my default organisation tenant, however the organisational account in my home tenant is a guest account in multple Azure Tenants (that I have been delegated permissions in) that I can support. I would like to know if it is possible to configure CCO Insights to target alternative tenants than my default organisational tenant acquired through providing my logon credentials.

**Comment by jason-ukr** [comment]
I have the same question, is it possible to add the ability to select a tenant for control panels and infrastructure? 
Even if you specify the desired tenant when connecting to the infrastructure control panel, the information is still displayed for the tenant in which the account was created.
If this is already implemented, then there are not enough step-by-step instructions. Thank you!

**Comment by josunefon** [comment]
Hi,

This is something that is already implemented, If you have the correct rights on multiple tenants you'll see all the resources:

![image](https://user-images.githubusercontent.com/39730064/194909257-59d849fc-5de9-4aed-bee8-96f86cacf433.png)

You need to follow this procedure:
https://learn.microsoft.com/en-us/azure/lighthouse/how-to/onboard-customer

And after that add a filter in the dashboard with the tenant display name

**Comment by CarlH2** [comment]
HI,  Thanks for the answer.  My point is I do not want the tool to try and even gatehr any infomration on my Default tenant as I do not want any information related to my deafult tenant (to which I will have little access) included in the PowerBI data provided and discussed with the organisation whose AAD I am assisting them with (it is useful to understand I have a guest account in many Teannts).  I am needing a method of ensuring the tool set only collects data from a defined specific tenant. Thanks.

**Comment by josunefon** [comment]
Something like this was done in the past for a customer, so you can create a new table with all the **SubscriptionIds** of the subscriptions from where you want to retrieve data and replace the existing "**All Subscriptions**" table. If you have the correct rights, you'll not have problems retrieving the data.

As you can see, the API calls are using the SubscriptionIds:
`   GetPages(GetManagementURL(AzureKind)&"/subscriptions/"&SubscriptionId&"/resources?api-version=2021-04-01"),`

**Comment by CarlH2** [comment]
Thanks for the information, however I am not a PowerBI developer or regular user of PowerBI, and I am also new to CCO Insights.  To be honest I really more interested in the data the tool set gathers rather than how the data is gathered.  Is there a step by step guide on how to achieve this. Thanks (and apologies for being a bit thick).
