### ISSUE TITLE
Dashboards Error - loading blocked by failures with other queries

### ISSUE THREAD

**Issue by matthansen0** [Azure/CCOInsights#271]
First, I looked through all the other closed issues, including https://github.com/Azure/CCOInsights/issues/215, and I still get this issue. 

**Screenshots**

![image](https://user-images.githubusercontent.com/23407342/191771490-88f490b9-e4c1-4cf0-87e4-1bd314a45cad.png)

![image](https://user-images.githubusercontent.com/23407342/191771567-993bb05e-f15f-4533-ba78-39a1b0b240e1.png)

![image](https://user-images.githubusercontent.com/23407342/191771807-ef045a7f-c29c-42d4-a442-6d8258ee3e9c.png)

I have my security and privacy settings configured as described: 

![image](https://user-images.githubusercontent.com/23407342/191774814-c8ef4d7c-aa2c-469a-857e-84c37e36a5cf.png)

![image](https://user-images.githubusercontent.com/23407342/191774853-3bb2a61d-b805-49ca-b548-510aac886e1a.png)

I also have my connector stored like is described: 

![image](https://user-images.githubusercontent.com/23407342/191775345-f36971eb-ed31-4455-a718-ae6390511c15.png)

Paused OneDrive too: 

![image](https://user-images.githubusercontent.com/23407342/191775475-c024a191-ffdd-440f-90e4-8011d4e4dda1.png)

I validated that the Connector is registering in Power BI as well: 

![image](https://user-images.githubusercontent.com/23407342/191776926-84e4be64-4736-4cb9-a21a-617ec08ceb32.png)

I've tried this against my MSDN tenant, PayGo Tenant, and EA Tenant on a Windows 11 machine that's domain joined, one that's Windows 11 Home, and from a Server 2016 Azure VM all with the same errors. The dashboard in question is Infra, but Governance throws a similar error.

**Comment by Brianbla** [comment]
I happen to working on this same error with another user using the Infrastructure dashboard. There are 4 issues related to this error but the resolution was for the Governance dashboard - https://github.com/Azure/CCOInsights/issues?q=is%3Aissue+%22Loading+blocked+by+failures+with+other+queries%22

User PowerBI and file settings are confirmed correct according to the docs as you posted above.

I have gone ahead and also created a discussion for my issue.

**Comment by matthansen0** [comment]
> 
That's very interesting. When I git clone the repo I get a different hash of the .mez compared to when I download the raw file from a browser. That solved my issue. Maybe we should post the hash of that connector? 

![image](https://user-images.githubusercontent.com/23407342/193307716-e3843f48-ba5f-4f68-8365-bb13cc47f352.png)
