### ISSUE TITLE
Incorrect secure score metrics on Governance dashboard

### ISSUE THREAD

**Issue by mpalagir** [Azure/CCOInsights#273]
Hi @TomazMlakar /Team,

Hope you are doing well.

Please be informed that, there is some inconsistency in the metrics of secure score and healthy, unhealthy resources count. Could you help me understand why it is showing incorrect metrics. We have secure score like 78% but in the dashboard it is reflecting as 83% along with incorrect resources count from Governance dashboard.

Looking forward to hearing from you.

Thank you.

**Comment by josunefon** [comment]
Hi,

Can you include a screenshot? we're checking the secure score numbers and we see no problems:

![image](https://user-images.githubusercontent.com/39730064/198084439-06b79d91-a3e0-41dd-925a-170cecb0c1f0.png)

**Comment by mpalagir** [comment]
Hi @josunefon,

Thanks for responding to my query.

Please find the attached below screenshot to make it easy understanding which one i was referring to.

![image](https://user-images.githubusercontent.com/105036831/200242687-97c543ba-6671-4740-b357-e64bfce4c923.png)

I was referring to the overall/consolidated secure score from **Security & Compliance tab**. 

Lastly kindly update me if we have any updated Power BI report for Azure Policies. Last time I understood that your team was working on it to troubleshoot further. Could you please update me on that as well.

Thank you.

**Comment by josunefon** [comment]
For the policies issue, please take a look to [this new version](https://github.com/Azure/CCOInsights/raw/c50b614986f34fe1dc5981f4ff17be4d28fc5739/dashboards/CCODashboard-Governance/CCO%20Power%20BI%20governance%20dashboard%20v2.7.pbit) of the dashboard

The API call was not paging correctly (this problem was already fixed and we have the PR pending to be approved)

**Comment by mpalagir** [comment]
Hi @josunefon,

Kindly let me know, once if this is completed too.

Thank you.
