### ISSUE TITLE
Incorrect blueprint version being published

### ISSUE THREAD

**Issue by d-ariho** [Azure/CCOInsights#275]
Hi team,

The Azure blueprints category is very useful thank you for this. The only issue is that it is not showing the latest version of the blueprint we have in the portal. Rather it is showing the oldest or an older version. I have cross-checked this with the Azure portal and there are quite a few discrepancies in the data. 

Is there a way to change this or is this something that is being worked on. This is of urgent need so an immediate response would be most welcome 😃

**Comment by d-ariho** [comment]
Our blueprint custom names and definitions are correct. The only issue we have is the versions that are showing in the blueprint artifacts table are incorrect.
We have numerous versions, and the dashboard is pulling the oldest version of these blueprints rather than the latest one, so the data is unreliable.

**Comment by josunefon** [comment]
If you want to see all the Blueprint artifact versions you need to go to the advanced editor and delete this step from the **CC Published Blueprints** Table

![image](https://user-images.githubusercontent.com/39730064/204357319-2047cef5-e2b1-4cd5-b319-14d0dd011c6e.png)
