### ISSUE TITLE
Visualize data for multiple tenants in CCO governance reports

### ISSUE THREAD

**Issue by xelizondo** [Azure/CCOInsights#288]
Can someone tell me how to make it possible to visualize data from multiple tenants?
I have tried:

1. Created a real user (like for service purposes) and tenant permissions tenant. Member of Global Reader AAD RBAC role in your Corp tenant, a license for a mailbox and PBI (E5 covered both).  Member of Reader Azure RBAC role in at the Root Management group 
2. In tenant 2 tenant, invited the service user as guest on tenant 2. 
3. Service user accepted the invitation. 
4. Made the guest user member of Global Reader role and Reader role at the Azure Root Management group on tenant 2 
5. Signed in PBI Desktop with the user account in tenant 1 and also when loading the CCO PBI reports (*.pbit file)
6. The CCO report doesn't pull the information from the Azure tenant 2 that the account has access to tenant 2 

Am I supposed to do something else or what should I do?

**Comment by xelizondo** [comment]
@pfayika1 ? any clues who could help me with this?

**Comment by josunefon** [comment]
Hi @xelizondo, guest accounts are not working if you don't force the dashboard creating a custom table with all the subscriptionIds in your tennant and in all the other tenants.

If you want to pull the data using the same user without modifying the actual data model/tables you need to apply [resource delegated management](https://learn.microsoft.com/en-us/azure/lighthouse/how-to/onboard-customer) to your user. Currently this is the only way as it's mentioned in the [doc](https://github.com/Azure/CCOInsights#cco-azure-infrastructure-dashboard-report-pages) (**Important Note**).
