### ISSUE TITLE
us-government Connect CCO Dashboard to your azure subscription 400 bad request

### ISSUE THREAD

**Issue by jrudley** [Azure/CCOInsights#310]
![image](https://user-images.githubusercontent.com/1934411/230938291-ffba04a8-c62d-459f-b8c6-716830d23a52.png)

Bad request when trying to get a token it seems.

**Comment by jmanuelcorral** [comment]
Hello,

  Actually we don't have a US-Government Subscription for tests, could you give more details that what steps are you doing? this will be more easy for us to understand and try to find the solution.

Thank you.
