### ISSUE TITLE
Multiple tenant 

### ISSUE THREAD

**Issue by supercloudnz** [Azure/CCOInsights#322]
How can you use these dashboards as an indirect reseller or direct bill partner/ direct provider ?

We are an MSP and would like to use these dashboard for of our customer tenant, how can we achieve this or is this feature you can add to your road map?

**Comment by jmalco-bp** [comment]
I believe you need an account on each of the tenants with Global Reader access.

**Comment by supercloudnz** [comment]
All Azure subscriptions provisioned for customers has a foreign principal assigned and the users in admin agent group frpm partner tenant have full access to those subscriptions. Can these users access the CCO insight dashboard? I have tried using the access and unable to use the report , gives multiple errors.
