### ISSUE TITLE
Governance Dashboard can't load data

### ISSUE THREAD

**Issue by One946** [Azure/CCOInsights#323]
After diligently following the installation instructions provided in the video tutorials, we have been unable to successfully import data into the dashboards. We have ensured the creation of the "Custom Connectors" directory under the local Documents directory, not the one hosted on SharePoint. Furthermore, we have set the language in PowerBI Desktop to English. To illustrate the issue more clearly, we are attaching a screenshot. It is important to note that we are utilizing the latest version of PowerBI Desktop.

![PowerBIError](https://github.com/Azure/CCOInsights/assets/26185898/ce74ddba-48b8-4287-8c5d-5462a7504f4a)

**Comment by bmvalente** [comment]
Have you check the [Governance Dashboard deployment guide](https://github.com/Azure/CCOInsights/wiki/Governance%20Dashboard%20-%20Deployment%20Guide)?
