### ISSUE TITLE
Infrastructure Dashboard

### ISSUE THREAD

**Issue by red-erik** [Azure/CCOInsights#326]
Hello,
I'm not able, in any way, yo open CCOInfradashboard v9.2.pbit.
Every time PBI responds it's corrupted (see attachment)
![Power_BI_CCO](https://github.com/Azure/CCOInsights/assets/10245160/24bca779-f90e-4e5f-b6d9-59ea75222b8b)

Regards,
Red.

**Comment by red-erik** [comment]
Hello,
any news from your side ?

Thanks,

Red.

**Comment by red-erik** [comment]
Hello,
still waiting for some help.
Thank you in advance.

Regards,
Red.

**Comment by DrDonoso** [comment]
Hello,

Did you change the [data extensions to allow any extension to load without validation or warning](https://github.com/Azure/CCOInsights/wiki/Infrastructure-Dashboard-Deployment%20Guide#:~:text=Then%20go%20to%20Power%20BI%20Options%20and%20under%20Global%20category%20in%20the%20Security%20section%2C%20select%20(Not%20Recommended)%20Allow%20any%20extension%20to%20load%20without%20validation%20or%20warning%20and%20click%20OK.)?

Thanks.

**Comment by red-erik** [comment]
Hello,
sure I did it.
![image](https://github.com/Azure/CCOInsights/assets/10245160/ad6a0187-d845-4608-a2aa-94b018cd55ef)

Regards,
Red.

**Comment by DrDonoso** [comment]
Could you review the path where the connector is stored? It should be at The path should be C:\Users%username%\Documents\Power BI Desktop\Custom Connectors.

[Did you try also storing it in the OneDrive folder](https://github.com/Azure/CCOInsights/wiki/Infrastructure-Dashboard-Deployment%20Guide#:~:text=The%20path%20should,will%20be%20recognized.)?

**Comment by red-erik** [comment]
Hello,
the path for Power BI is this
C:\Users\xxxxxx.yyyyyyy\Microsoft\Power BI Desktop Store App\Custom Connectors
and I already copied it to OneDrive too
C:\Users\xxxxxxx.yyyyyyy\OneDrive - Company Name\Documenti\Power BI Desktop\Custom Connectors
but I never see the connector ad an available source.
Regards,
Red.

**Comment by DrDonoso** [comment]
The Documents folder could be in OneDrive. In that case, the folder would appear as {OneDrive}\Documents\Power BI Desktop\Custom Connectors\. However, OneDrive is usually mapped to your local folder which results in the end path C:\Users\<username>\<OneDrive folder>\Documents\Power BI Desktop\Custom Connectors\.

Can you change the path as it is not supported from:
```
C:\Users\xxxxxx.yyyyyyy\Microsoft\Power BI Desktop Store App\Custom Connectors
```

to:

```
C:\Users\xxxxxx.yyyyyyy\Microsoft\Power BI Desktop\Custom Connectors
```

See the [referenced issue](https://speckle.community/t/power-bi-connector-not-showing-up/5235/14#:~:text=George_Thachil,Community%20member).

**Comment by red-erik** [comment]
Hello,
the existing path is
C:\Users\xxxxx.yyyyy\Microsoft\Power BI Desktop Store App\Custom Connectors
but if the path is hard coded, I can manually create
C:\Users\xxxxxx.yyyyyyy\Microsoft\Power BI Desktop\Custom Connectors
in any case, if I manually add the custom connector, when I open (file-->Open) the Pbit it opens a new Power BI instance without the connector, so hitting the error.

C:\Users\xxxxxx.yyyyyyy\Microsoft\Power BI Desktop\Custom Connectors [NOT WORKING]
C:\Users\xxxxxx.yyyyyyy\Documents\Microsoft\Power BI Desktop\Custom Connectors [NOT WORKING]
C:\Users\xxxxxx.yyyyyyy\Documents\Microsoft\Microsoft Power BI Desktop\Custom Connectors [NOT WORKING]

The same with OneDrive path
I'm not able to open both into the same instance

Regards,
Red.

**Comment by DrDonoso** [comment]
Sorry, I miswritten it.

It should be at 
```
C:\Users\xxxxxx.yyyyyyy\Documents\Power BI Desktop\Custom Connectors
```

**Comment by red-erik** [comment]
Hello,
still not working, so probably a problem on my side but using Windows 11 (latest) and Powe BI Desktop (latest).
It would be great having it working on a server side with auto refresh of all Dashboards.
Thank you for your help.

Regards,
Red.
