### ISSUE TITLE
Governance Dashboard can't load data

### ISSUE THREAD

**Issue by malexcarvalho** [Azure/CCOInsights#330]
After following the steps in the link below to implement the Governance Dashboard:
https://github.com/azure/CCOInsights/wiki/Governance%20Dashboard%20-%20Deployment%20Guide#installing-the-custom-connector

the following errors appeared when loading data "The column 'Column1' of the table wasn't found."
![image](https://github.com/Azure/CCOInsights/assets/126713513/2bd70041-0d2c-4555-90bf-00a83ebe789c)

**Comment by bmvalente** [comment]
Which user account are you using? See our [troubleshooting guide](https://github.com/azure/CCOInsights/wiki/Troubleshooting%20Guide#errors-regarding-missing-column1-on-refresh)

**Comment by malexcarvalho** [comment]
This is my user account that I'm using:
![image](https://github.com/Azure/CCOInsights/assets/126713513/553f5d67-2a52-4412-9b0e-2e0ca7292038)

**Comment by cyang926** [comment]
I am getting the same error.  Were you able to find a solution?  I am using an account from the same AAD tenant.  Am I missing some sort of permissions withing the tenant?

**Comment by bmvalente** [comment]
@malexcarvalho please use an account from the same AAD tenant. @cyang926 Have you gone through the [troubleshooting guide](https://github.com/azure/CCOInsights/wiki/Troubleshooting%20Guide#errors-regarding-missing-column1-on-refresh)?
