### ISSUE TITLE
Infrasdashboard 9.2 loading of graph.window.net

### ISSUE THREAD

**Issue by bumbo73** [Azure/CCOInsights#331]
I'm having a issue loading the graph.window.net content. It seems the other components are loaded (management, connected to the connector) but the graph component is still trying to load. I have about 90 subscriptions and they are finished as it says "loaded" but nothing for the graph. Any ideas how to get it working. I have followed the guide to the T. It's been like this for hours. The Governance dashboard loaded fine. Help?
![Screenshot 2024-03-06 233504](https://github.com/Azure/CCOInsights/assets/55373621/39afcbc1-c7ca-4d89-98d7-f125d6934cef)

**Comment by bmvalente** [comment]
Did you follow the [Troubleshooting Guide](https://github.com/Azure/CCOInsights/wiki/Troubleshooting%20Guide)?

**Comment by bumbo73** [comment]
Yes - I did. It's not giving any errors. Just taking a long time as the graph part isn't loading any records/results. 

Just wondering what I'm doing wrong.

**Comment by bumbo73** [comment]
I have used my organization credentials and it accepts them without error

**Comment by bmvalente** [comment]
Did you double check with the [Infrastructure dashboard deployment guide](https://github.com/Azure/CCOInsights/wiki/Infrastructure-Dashboard-Deployment%20Guide)?

**Comment by francesco1119** [comment]
We have 16 Subscriptions. 
Most of the tables refresh immediately, then there are a few that load very slow. 
Take **RBAC Role SP, Users and Groups**, as you can see it moves from 1,834 to 1,840... it means it's loading some rows but it takes time: 

![Power BI loading](https://github.com/Azure/CCOInsights/assets/3397477/34c2d6a6-91c8-4c95-847a-9365b14b6004)

So if you have 90 Subscriptions this might lead to a timeout. 
...if there is a timeout involved @bmvalente

**Comment by bmvalente** [comment]
@bumbo73 / @francesco1119 Not all Azure APIs have the same throughput, so when loading tables in parallel, some finish first than others.
