### ISSUE TITLE
Governance Dashboard - Hierarchy Overview Visual Not Displaying

### ISSUE THREAD

**Issue by echosummet** [Azure/CCOInsights#332]
This is a duplicate of Issue 325 https://github.com/Azure/CCOInsights/issues/325

I apologize for creating a duplicate issue, but I did not see a way to re-open the existing one, which has gone stale.

**Describe the bug**
After loading the data without issues, the report fails to display the hierarchy visual. 
![Screenshot 2024-03-13 132154](https://github.com/Azure/CCOInsights/assets/74855801/720cb0b3-8615-4b39-979e-9d2997b29c8c)

I am able to see parts of the hierarchy tree by playing around with the CC GetEntities parameters, but I havent found a way to show the entire tree with images etc. 

**To Reproduce**
1. Load template
2. Authenticate to Azure
3. Open the Hierarchy Overview tab

**Expected behavior**
The hierarchy displayed

**Comment by bmvalente** [comment]
Have you checked the [Governance Dashboard deployment guide](https://github.com/Azure/CCOInsights/wiki/Governance%20Dashboard%20-%20Deployment%20Guide)?

**Comment by echosummet** [comment]
> Have you checked the [Governance Dashboard deployment guide](https://github.com/Azure/CCOInsights/wiki/Governance%20Dashboard%20-%20Deployment%20Guide)?

Yes, I have. 

Is there something in it that you are thinking could be related to the visual not displaying that I am overlooking?

**Comment by francesco1119** [comment]
And I agree with @echosummet .
same problem here.

**Comment by bmvalente** [comment]
@echosummet / @francesco1119 We believe this functionality may have been broken by one recent update from PowerBI. We have put this in our backlog but as a workaround, you can remove the image that is in the "hierarchy" window and you'll see the "raw" hierarchy information.

**Comment by echosummet** [comment]
> @echosummet / @francesco1119 We believe this functionality may have been broken by one recent update from PowerBI. We have put this in our backlog but as a workaround, you can remove the image that is in the "hierarchy" window and you'll see the "raw" hierarchy information.

Thank you for the update @bmvalente! 

I have been removing the image as you described which has been a sufficient workaround for me. Thanks again

**Comment by echosummet** [comment]
Fix added to backlog, but interim workaround is good.
