### ISSUE TITLE
Expression.Error: We cannot convert the value null to type Text.

### ISSUE THREAD

**Issue by francesco1119** [Azure/CCOInsights#333]
**Describe the bug**
After following your videos I cannot setup the very first dashboard: 

```
Expression.Error: We cannot convert the value null to type Text.
Details:
    Value=
    Type=[Type]
```

And most of the queries are having the same issue

![image](https://github.com/Azure/CCOInsights/assets/3397477/54e207e4-5c72-4bad-b734-43d53e365be3)

**To Reproduce**
Follow this video: https://www.youtube.com/watch?v=3lXcSaGtlx4

**Expected behavior**
It should work like in the video 

**Screenshots**

![image](https://github.com/Azure/CCOInsights/assets/3397477/3e8f1a6d-64df-420e-b329-bfb324cccc7f)

**Desktop (please complete the following information):**
 - OS: Windows 12
 - Browser: Chrome
 - Version: Latest version

**Comment by bmvalente** [comment]
Have you double checked the [Governance Dashboard deployment guide](https://github.com/Azure/CCOInsights/wiki/Governance%20Dashboard%20-%20Deployment%20Guide)?

**Comment by francesco1119** [comment]
Being capable of reading a good documentation is definitely a step that will allow you to go through the finish line. 

I'm going into deep diving those dashboards in the next few weeks and I might open some tickets. 
Microsoft should give a bit of love to this COOInsight. The project is good but it looks abandoned. 
 
Thank you
