### ISSUE TITLE
CCO Dashboard Governance does not work after first successful load

### ISSUE THREAD

**Issue by phunghuan43** [Azure/CCOInsights#334]
**Describe the bug**

CCO Dashboard Governance does not work after first successful load.

After  first successful load, it keeps showing error as screenshot.

I have tried reinstall PowerBI but it seems not to fix it.

**To Reproduce**
1. Go to "https://www.youtube.com/watch?v=3lXcSaGtlx4&t=117s"

**Screenshots**
![1](https://github.com/Azure/CCOInsights/assets/150769976/06a9341e-4f6e-40d4-ad1d-7fcbd8ab7364)

![2](https://github.com/Azure/CCOInsights/assets/150769976/2d2aac12-a61d-415b-9694-149263491e9b)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Power BI desktop version:  2.127.1080.0 64-bit (March 2024)

**Comment by phunghuan43** [comment]
any idea?

**Comment by bmvalente** [comment]
@phunghuan43 did you follow the credentials guidance section in the [Governance deployment guide](https://github.com/Azure/CCOInsights/wiki/Governance%20Dashboard%20-%20Deployment%20Guide)?

**Comment by phunghuan43** [comment]
> @phunghuan43 did you follow the credentials guidance section in the [Governance deployment guide](https://github.com/Azure/CCOInsights/wiki/Governance%20Dashboard%20-%20Deployment%20Guide)?

Yes, I did follow deployment guide, but still not working. It only works once at the first run. After that It got errors as above.

Any idea?

**Comment by bmvalente** [comment]
@phunghuan43 we've updated the dashboard to v2.8 to solve some other issues we were facing, but can you give it a go with the new version to see if this issue is still happening? Thank you

**Comment by phunghuan43** [comment]
> @phunghuan43 we've updated the dashboard to v2.8 to solve some other issues we were facing, but can you give it a go with the new version to see if this issue is still happening? Thank you

That is good news, I'll try it and let you know soon! Thank you

**Comment by phunghuan43** [comment]
> @phunghuan43 we've updated the dashboard to v2.8 to solve some other issues we were facing, but can you give it a go with the new version to see if this issue is still happening? Thank you

Hello, 

After trying new version on 2 different computers, it still gets same error as below. It happens to all Dashboard

![image](https://github.com/Azure/CCOInsights/assets/150769976/8b371f6b-04a9-45b1-83d9-4b166e76b6f4)

any idea?

**Comment by phunghuan43** [comment]
May I also know if CCO can help to track costing?

**Comment by josunefon** [comment]
Hi @phunghuan43 yes, you can add the cost management API and create a relationship within the existing data model, however this is not tested in the actual solution and we can't offer support if something happens
