### ISSUE TITLE
PBI - CCO Power BI governance dashboard 

### ISSUE THREAD

**Issue by malexcarvalho** [Azure/CCOInsights#335]
When opening and updating the 'CCO Power BI governance dashboard' for the first time, the following error appears in the graph on the first page.
![image](https://github.com/Azure/CCOInsights/assets/126713513/b0d2e728-4446-4952-96e6-23fde879e4a7)

How can I fixe this situation?

**Comment by bmvalente** [comment]
@malexcarvalho  Please refer to [this](https://github.com/Azure/CCOInsights/issues/332#issuecomment-2015447413) as a potential workaround

**Comment by bmvalente** [comment]
@malexcarvalho fix with version 2.8 of the Governance Dashboard
