### ISSUE TITLE
refresh issue 

### ISSUE THREAD

**Issue by mikewolly** [Azure/CCOInsights#365]
### Pre-requirements

- [X] Reviewed the Deployment guide
- [X] Reviewed the Troubleshooting guide
- [X] Reviewed the YouTube channel
- [X] Reviewed the GitHub Issues list

### What dashboard are you reporting an issue on?

Infrastructure Dashboard

### What happened?

I have the desktop version but somehow its not refreshing the "Get Advisor Score" table.
![Screenshot 2024-06-12 041509](https://github.com/Azure/CCOInsights/assets/172482598/dc2777ac-f0f4-4b86-beab-ea6b21117cce)

### Steps to reproduce

the report was shared to me from a colleague who works as a Security analyst. As you can see in the picture its a different version than what you have in 5 of your Youtube videos. I just need help refreshing the data and specifically that table.

**Comment by josunefon** [comment]
Hi @mikewolly the solution was already answered by the bot, apologies for now answering here. https://github.com/Azure/CCOInsights/issues/367
